### Overview

The liver is the central metabolism organ of the human body.
It is located in the upper right side of the body, protected by the lower ribs.<br>
With a weight of approximately 1500 grams, it is the largest gland of the body.  
Besides metabolism, the liver is also responsible for producing a variety of coagulation factors and hormones.<br>
The organ is also essential for removing external substances like alcohol and medications from the blood stream. 
For 2020, the WHO estimated the number of new cases of liver cancer (ICD C22) to be 905 677 (CI:[884695-927157]).  
According to the WHO, liver cancer caused 830 000 deaths worldwide in 2020, a number only exceeded by lung cancer (1.8 million deaths worldwide) and colorectal cancer (935 000 deaths worldwide).

### Epidemiology

In most sources, liver cancer prevalence, incidence and mortality for men is about 2-3 times as high as it is for women.<br>
WHO data estimates that in 2020, 632 000 men and 273 000 women were diagnosed with liver cancer and that in the same year, 578 000 men and 253 000 women in association with liver cancer. For men, liver cancer mortality is only surpassed by lung cancer mortality.<br>
For women on the other hand, liver cancer only takes sixth place in terms of total deaths, with sex-specific tumours like breast and uterus cancer accounting for more deaths.<br>
For Germany, the most recent data available describes new cases and mortality in 2017. In this year, 6040 men and 2903 women were diagnosed with liver cancer and 5213 men and 2697 women died in association with liver cancer.<br>

### Risk factors 

Chronic hepatitis B or hepatitis C infection greatly increase the risk of developing liver cancer.<br>
Cirrhosis, an irreversible process in which healthy liver tissue is replaced by scar tissue, thus losing its functions, is also a prominent risk factor for liver cancer.<br>
Excessive alcohol consumption, obesity, diabetes and nonalcoholic fatty liver disease are also associated with an increased risk for liver cancer.

### Symptoms

There are multiple symptoms, but the one that displays the liver function most is the so called jaundice, also known as Icterus, where your skin and especially your eyes turn yellow. <br>
Other symptoms as a loss of appetite, feeling generally unwell as well as having a loss of energy and tireness are widely considered as symptoms of cancer of any type.

### Diagnosis

The diagnostic process is the same as for most cancer types. Typically there are blood tests to look for tumour markers as well as a biopsy, in that case of liver cells.<br>
Other possible diagnostic options are PET scans, CTA or MRI scans.

### Treatment

* Surgery
* Ablation
* Embolization Therapy
* Radiation Therapy
* Targeted Drug Therapy
* Immunotherapy
* Chemotheraphy

### Prevention

As HBV and HCV infections are major risk factors for the development of liver cancer, taking precautions against these viruses can help prevent liver cancer.<br>
Protection against hepatitis B can be obtained by a vaccine which is recommended for children and adults at risk in many countries including Germany, the US and the UK.<br>
Hepatitis C is transmitted parenterally and sexually, therefore prevention includes only using clean, disinfected needles and syringes as well as being aware of the health status of sexual partners.<br>
In the case that an infection with HBV or HCV could not be prevented, treatments reducing liver cancer risk are available.<br>
In a 2007 meta-analysis, increased coffee consumption was found to be associated to a lower risk of liver cancer.<br>
Reducing alcohol consumption and keeping a healthy weight can also help reduce liver cancer risk.

### Sources

* https://www.nhs.uk/conditions/liver-cancer/ <br>
* https://www.who.int/news-room/fact-sheets/detail/cancer <br>
* https://www.wcrf.org/dietandcancer/liver-cancer-statistics/ <br>
* https://www.wcrf.org/dietandcancer/liver-cancer/ <br>
* https://www.cdc.gov/cancer/liver/index.htm <br>
* https://www.krebsdaten.de/Krebs/DE/Content/Krebsarten/Leberkrebs/leberkrebs_node.html <br>
* https://www.mayoclinic.org/diseases-conditions/liver-cancer/symptoms-causes/syc-20353659 <br>
* https://www.sciencedirect.com/science/article/abs/pii/S0016508507005689 <br>

          
                         